### ISSUE TITLE
[BUG]: Improper alignment of footer with white spaces on left and right ride

### ISSUE THREAD

**Issue by harmeetsingh11** [harmeetsingh11/RefactorMate#1]
### Problem:
The footer is not properly aligned on the website. Currently, it is centered with some margins on the left and right side, resulting in noticeable white spaces on both sides.

### Expected Behavior:
The footer should be aligned correctly without excessive white spaces on the left and right. It should maintain a visually balanced appearance within the layout.

### Steps to Reproduce:
1. Visit the website.
2. Scroll down to the footer section.
3. Observe the alignment and white spaces on the sides.

### Screenshots (if applicable):
![footer](https://github.com/harmeetsingh11/RefactorMate/assets/130365071/7a6f691f-d03f-4dd9-ad91-c314b0abd10e)

### Environment:
- Browser: Chrome
- Device: Desktop

### Record
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues) 
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md) 
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md) 
- [ ] I want to work on this issue

**Comment by Saishreekouda** [comment]
hey can you assign this issue to me

**Comment by harmeetsingh11** [comment]
@Saishreekouda the issue has been assigned to you and you can start working on it.

**Comment by Hrx4** [comment]
heuy @harmeetsingh11  i want to work on this issue under JWOC

**Comment by SharmaDhruv2511** [comment]
if there is not any update i would like to work on this issue @harmeetsingh11 ??

**Comment by harmeetsingh11** [comment]
@SharmaDhruv2511 the issue has been assigned to you.

**Comment by SharmaDhruv2511** [comment]
![image](https://github.com/harmeetsingh11/RefactorMate/assets/102755411/d6ec33d5-309f-49e5-aeeb-49b2e88eeb95)

looks good? @harmeetsingh11

**Comment by harmeetsingh11** [comment]
@SharmaDhruv2511 first one! please add some padding to left and right side.

**Comment by SharmaDhruv2511** [comment]
![image](https://github.com/harmeetsingh11/RefactorMate/assets/102755411/0d9961cc-d033-4b80-b96c-f979e8d0fa52)

looks good? @harmeetsingh11
