### ISSUE TITLE
[Feature]: Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#39]
### Description

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Justification

Yes, the feature request is important because when issues are created in a project, it is important to provide immediate acknowledgment and guidance to the issue creator. However, manually commenting on every newly created issue can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling ignored or discouraged from further participation.

### Screenshots

![issue creation](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/e2b40672-a713-4d0b-8f64-817ebec52031)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
@Asymtode712 the issue has been assigned to you. You can start working on it.
