### ISSUE TITLE
[BUG]: Incomplete Code Display and Unnecessary Scrollbar in Original Code Input Box

### ISSUE THREAD

**Issue by harmeetsingh11** [harmeetsingh11/RefactorMate#4]
## Issue
The code entered in the `Original Code` input box is displayed at half of the height of the input box, and a scrollbar is added. The expected behavior is that if the content overflows the full height of the container, then the scrollbar should be added.

## Description
When entering code into the "Original Code" input box, the display behavior is not as expected. The code appears at only half of the height of the input box, and a scrollbar is added even when the content doesn't exceed the full height of the container.

## Steps to Reproduce
1. Navigate to the "Original Code" input box.
2. Enter code that exceeds the half height of the input box.

## Expected Behavior
The code should be displayed within the full height of the input box, and a scrollbar should only be added if the content exceeds the available vertical space.

## Actual Behavior
The code is displayed at half of the height of the input box, and a scrollbar is added even when the content doesn't overflow the full height of the container.

## Screenshots
![height](https://github.com/harmeetsingh11/RefactorMate/assets/130365071/11e6535e-ae8e-4913-a7e0-bffcf6a5e87d)

## Environment:
- Browser: Chrome

## Record
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues) 
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md) 
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md) 
- [ ] I want to work on this issue

**Comment by Quaxguy** [comment]
I would like to work on this issue. Assign me I'm a contributor under codepeak2023

**Comment by Albert-2** [comment]
hey @harmeetsingh11
May i contribute to this issue.....
Thank you.....!! :)

**Comment by harmeetsingh11** [comment]
@Albert-2 this issue has been assigned to you and you can start working on this issue.

**Comment by Albert-2** [comment]
![image](https://github.com/harmeetsingh11/RefactorMate/assets/90373859/469a64e6-2ea1-45c8-9195-1593613baf3a)

Hey @harmeetsingh11 
I've made the changes you asked for and made a PR too
Please review it and if in case i had missed something then please let me know
Thank You....

**Comment by harmeetsingh11** [comment]
@Albert-2 Thaks for making the PR. Can you please mention issue number in PR (Something like "Closes issue/Resolves issue #<issue number>"). 
I will review the changes tomorrow.

**Comment by Albert-2** [comment]
https://github.com/harmeetsingh11/RefactorMate/issues/4
here it is 
Okok

**Comment by Albert-2** [comment]
hey @harmeetsingh11
Kindly review the PR.....!!
