### ISSUE TITLE
[Feature]: Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#40]
### Description

This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Justification

The feature request is important because when contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.

### Screenshots

![PR raised](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/f5d6389f-a6c9-47a7-911f-53907cba10f8)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
@Asymtode712 the issue has been assigned to you.
