### ISSUE TITLE
[Feature]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#41]
### Description

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Justification

The feature request is important because when pull requests (PRs) are merged in a project, it is often important to provide consistent feedback or notifications to the contributors. Currently, this process can be manual and time-consuming, leading to inconsistent communication and delayed acknowledgments. This can frustrate both maintainers, who have to remember to comment, and contributors, who might feel their efforts are not promptly recognized.

### Screenshots

![PR merged](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/74758e96-66f8-4eb7-a74b-b54dc1df6a13)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
@Asymtode712 assigning to you, go for it.
