### ISSUE TITLE
[Feature]: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#42]
### Description

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Justification

Over time, repositories can accumulate a large number of open issues, including some that may no longer be relevant or actively worked on. Manually closing these old issues can be time-consuming and tedious.

### Screenshots

![Close Old Iss](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/2d83fca5-1583-4dbf-9562-2c61dd05ba8b)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
Good idea @Asymtode712 , but we don't need it at the moment because there are a limited number of issues. Feel free to pick up any other issues.

**Comment by Asymtode712** [comment]
@harmeetsingh11 sure
