### ISSUE TITLE
[Feature]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#43]
### Description

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Justification

Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

### Screenshots

![Close Old PRs](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/361418e9-21b7-45f1-90f5-7a87aea77df0)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
Good thought @Asymtode712 , but we don't need it at the moment because there are a limited number of PRs. Feel free to pick up any other issues.
