### ISSUE TITLE
[Feature]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#44]
### Description

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Justification

The feature request is important because it is related to the problem of lack of communication and acknowledgment when issues are closed in the repository. Contributors may feel neglected or uncertain about the status of their issues if they are closed without any feedback or acknowledgment. This can lead to frustration and a decrease in motivation to contribute further.

### Screenshots

![issue closed](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/ba35e054-5263-412a-9f7f-c61b17b76804)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 please assign me this issue under gssoc

**Comment by harmeetsingh11** [comment]
@Asymtode712 assigned to you.
