### ISSUE TITLE
[BUG]: Lack of Mobile Responsiveness in `Original Code` Box and `Refactor Code` Box

### ISSUE THREAD

**Issue by harmeetsingh11** [harmeetsingh11/RefactorMate#5]
## Problem
The `Original Code` box and the `Refactor Code` box are currently not mobile responsive. When viewed on smaller screens, the layout does not adjust appropriately, leading to usability issues.

## Description
The current layout of the `Original Code` box and the `Refactor Code` box does not adapt well to smaller screen sizes, making it difficult to view and interact with the content on mobile devices.

## Steps to Reproduce
1. Open the application on a mobile device or use a responsive design testing tool.
2. Navigate to the `Original Code` box or the `Refactor Code` box.

## Expected Behavior
The layout of the `Original Code` box and the `Refactor Code` box should adapt to smaller screen sizes, providing a user-friendly experience on mobile devices.

## Actual Behavior
The `Original Code` box and the `Refactor Code` box do not adjust to smaller screens, causing usability issues on mobile devices.

## Screenshots
![responsive](https://github.com/harmeetsingh11/RefactorMate/assets/130365071/5ad2fd62-682f-4079-a7ec-82ca2464d735)

## Environment
- Browser: Chrome

## Record
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues) 
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md) 
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md) 
- [ ] I want to work on this issue

**Comment by Quaxguy** [comment]
Assign me please as I'm a contributor in codepeak

**Comment by harmeetsingh11** [comment]
@Quaxguy ,the issue has been assigned to you and you can start working on it :)

**Comment by Quaxguy** [comment]
![Screenshot 2023-12-10 125335](https://github.com/harmeetsingh11/RefactorMate/assets/98159458/a84b88ab-6164-4d46-9280-88ee316de673)
i have a doubt i cant start the backend server though i have installed dependencies and the frontends working fine after adding my api key as a string the terminal throws this error could you please help me out 
![Screenshot 2023-12-10 125335](https://github.com/harmeetsingh11/RefactorMate/assets/98159458/ee977cd8-2020-4830-a0b3-d1238cd59d06)

**Comment by Quaxguy** [comment]
i tried modifying tsconfig file but nothing works

**Comment by Quaxguy** [comment]
@harmeetsingh11 can u clarify the doubt for me please

**Comment by harmeetsingh11** [comment]
Try these solutions:
1. Try running these commands-

```bash
ts-node --esm index.ts 
Or 
ts-node-esm index.ts
```
2. Remove "type": "module" from package.json file

**Comment by Quaxguy** [comment]
well tried both of them not working for me

**Comment by Albert-2** [comment]
hey @Quaxguy
I must say what a project man ssly loved it
Appreciate 🙌
And I really like to be the part of it
can you please assign me this issue
THANK YOU FOR CONSIDERING..... :)

**Comment by harmeetsingh11** [comment]
@Quaxguy what's the progress? Are you working on this issue?

**Comment by Albert-2** [comment]
hey @harmeetsingh11
can you please assign it to me if no one is still working on it......

**Comment by harmeetsingh11** [comment]
@Albert-2 once I find out that no one is working on this issue, I will assign it to you.

**Comment by Albert-2** [comment]
okok

**Comment by Quaxguy** [comment]
@harmeetsingh11 I'm working on it I need half a day I'll send a pr tomorrow

**Comment by harmeetsingh11** [comment]
@Albert-2 , @Quaxguy is currently working on this issue, you can look for other issues in issues section or can create a new issue.

**Comment by harmeetsingh11** [comment]
@Quaxguy What's the update? It has been a considerable amount of time since the issue was assigned to you.

**Comment by Albert-2** [comment]
hey @harmeetsingh11
If you want then i can contribute to this issue

**Comment by harmeetsingh11** [comment]
@Albert-2 the issue has been assigned to you and you can start working on it.

**Comment by Albert-2** [comment]
okok thank you

**Comment by Albert-2** [comment]
hey @harmeetsingh11 
I have made changes 
just one doubt i have is in this PR too i don't need to include those three files

**Comment by Albert-2** [comment]
for desktop:
![image](https://github.com/harmeetsingh11/RefactorMate/assets/90373859/db5055d3-27bc-44fe-aae5-b31a2c832b97)

for mobile:
![image](https://github.com/harmeetsingh11/RefactorMate/assets/90373859/2c3b9583-c0ef-44bb-89f2-6549e6d4baea)

**Comment by harmeetsingh11** [comment]
@Albert-2 it looks good. Yes, you don't have to include `package.json` and `package-lock.json ` files in commits, include only files in which changes have been made.

**Comment by Albert-2** [comment]
hey @harmeetsingh11 
Kindly Review the PR 
Here it is https://github.com/harmeetsingh11/RefactorMate/pull/14
Thank You......
