### ISSUE TITLE
[DOCS]: Missing Learn.md file 

### ISSUE THREAD

**Issue by debangi29** [harmeetsingh11/RefactorMate#51]
### Issue Description

Add Learn.md file as instructed by Gssoc guidelines

### Proposed Solution (optional)

I can add the Learn.md file if assigned to do so
Please assign me the task @harmeetsingh11 

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by harmeetsingh11** [comment]
@debangi29 Not needed as of now, closing this issue. If you have any further questions or concerns, please feel free to open a new issue.
