### ISSUE TITLE
[Feat]: Enhance User Experience-rearrange code refactor section and improve project documentation

### ISSUE THREAD

**Issue by Devesh-Daku** [harmeetsingh11/RefactorMate#6]
**Is your feature request related to a problem? Please describe.**
As this project serves as a useful tool ,I'd like to suggest having to useful part(the code refactor part ) at the top

**Describe the solution you'd like**
I'd like to suggest having to useful part(the code refactor part ) at the top
 just after a heading (that guides brefily about how to use the tool below )  then giving all the details of what our project is, providing complete documentation below on how to use it and what this project is 

because scrolling down a lot in mobile and also a little scrolling in PC  makes a bit discomfort to use this tool

**Describe alternatives you've considered**

**Additional context**
![refactor](https://github.com/harmeetsingh11/RefactorMate/assets/121988601/3fa44d0f-1964-4dc5-8ae9-d646d57df4b1)

**Comment by Devesh-Daku** [comment]
I'd like to work on this issue

**Comment by harmeetsingh11** [comment]
@Devesh-Daku , the issue has been assigned to you and you can start working on it.
