### ISSUE TITLE
[Style]: add scroll to top button

### ISSUE THREAD

**Issue by sharmi4590** [harmeetsingh11/RefactorMate#62]
User experience enhances when there is less scrolling in the web pages , thus when the user scrolls down to visit the website it will not required to the user to again go back to the top by scrolling as it is a waste of time. Thus adding scroll to top button will take the user to the top in a click.
![stt](https://github.com/harmeetsingh11/RefactorMate/assets/102676949/0da8da8b-c94d-4350-bd20-9f1d961ba23e)

This is my previous work

![Screenshot (495)](https://github.com/harmeetsingh11/RefactorMate/assets/102676949/8cfd488b-891f-4537-ad41-4e655a22b9a3)

**Comment by harmeetsingh11** [comment]
@sharmi4590 the issue has been assigned to you. You can start working on it. Keep contributing:)

**Comment by pani2004** [comment]
@harmeetsingh11 is the issue still open?

**Comment by harmeetsingh11** [comment]
@sharmi4590 are you working on this issue?

**Comment by priyankMS** [comment]
I want to work on this feature under GSSOC 24 please add a label to it and assign it to me.

**Comment by sharmi4590** [comment]
> @sharmi4590 are you working on this issue?

Yes @harmeetsingh11 , I will do the PR by EOD
