### ISSUE TITLE
[BUG]: Visiblity issue in Benefits section on hover

### ISSUE THREAD

**Issue by nishant0708** [harmeetsingh11/RefactorMate#64]
### Description

when we hover on card text is not visible

### Steps to Reproduce

npm run frontend
go to benefits section and hover on cards

### Expected Behavior

text should be visible

### Actual Behavior

text is not visible

### Screenshots

![image](https://github.com/harmeetsingh11/RefactorMate/assets/101548649/4cfbaf08-6d4e-4e2e-ae89-81d8bf5f038e)

### Browser

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by harmeetsingh11** [comment]
@nishant0708 the issue has been assigned to you. Keep contributing:)
