### ISSUE TITLE
[BUG]: Alignment of the Linked In icon and updating the twitter logo

### ISSUE THREAD

**Issue by pani2004** [harmeetsingh11/RefactorMate#67]
### Description

The linked in icon is not properly aligned with the other icons and the twitter icon needs to be updated.

### Steps to Reproduce

Will update the twitter logo

### Expected Behavior

The Linked In icon should be aligned with the other icons

### Actual Behavior

Linked In icon is slightly below the other icons 

### Screenshots

![Screenshot 2024-06-08 140948](https://github.com/harmeetsingh11/RefactorMate/assets/154724111/a5e402a1-28e5-4db2-877c-2f399c4e60d9)

### Browser

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by pani2004** [comment]
@harmeetsingh11 Pls assign me this!!

**Comment by harmeetsingh11** [comment]
@pani2004 the issue has been assigned to you. You can start working on it. :)
