### ISSUE TITLE
[Style]: Hovering of arrow icon in hero section

### ISSUE THREAD

**Issue by pani2004** [harmeetsingh11/RefactorMate#71]
### Description

When the arrow icon is hovered I want to add a style in which it will point towards downward direction.

### Justification

This animation provides a clear indication that the button is interactive and encourages users to click.

### Screenshots

![Screenshot 2024-06-10 225353](https://github.com/harmeetsingh11/RefactorMate/assets/154724111/ef71e78f-0f44-498b-8b78-c4adf22ac8b7)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by pani2004** [comment]
@harmeetsingh11 Can I work on this?

**Comment by harmeetsingh11** [comment]
@pani2004 the issue has been assigned to you. Make sure to pull latest changes, now we are using `pnpm` package manager.
