### ISSUE TITLE
[Style]: Adding a suitable loader animation

### ISSUE THREAD

**Issue by Praneeth-2602** [harmeetsingh11/RefactorMate#73]
### Description

To improve user experience and provide visual feedback during the code refactoring process, it is suggested to add a loader animation. This will inform users that their request is being processed and reduce uncertainty during wait times.

### Justification

A loader animation improves user feedback, reduces uncertainty, and enhances the user experience by visually indicating that the code is being processed, making the tool feel more responsive and professional.

### Screenshots

https://github.com/harmeetsingh11/RefactorMate/assets/137754636/bd5d38b3-af23-4be3-96b7-6d2b19bc3f90

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by sanjay-kv** [comment]
I dont have access to this repo yet , kindly add me to it @harmeetsingh11

**Comment by harmeetsingh11** [comment]
@Praneeth-2602 Thanks for your suggestion. We've actually implemented a skeleton loading animation to provide visual feedback during the code refactoring process. Therefore, closing this issue.
