### ISSUE TITLE
[Feature]: Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [harmeetsingh11/RefactorMate#81]
### Description

A preloader is an essential feature for enhancing user experience by indicating the progress of loading content. It helps in keeping the users engaged while the main content is being fetched or rendered. Implementing a preloader can significantly improve the perceived performance of our application.

### Justification

**Enhanced User Experience:**
1. Users are informed about the progress of loading content, reducing uncertainty and frustration.
2. A preloader keeps users engaged and reassured that the application is functioning correctly.

**Improved Perceived Performance:**
1. By providing a visual indicator during loading, the perceived performance of the application is improved, making users feel that the application is faster.

**User Retention:**
1. A smoother loading experience helps in retaining users by preventing them from abandoning the application due to unresponsive or slow-loading screens.

**Consistency:**
1. A preloader ensures a consistent experience across different parts of the application, especially when loading large components or data-heavy pages.

**Customization:**
1. Customizable preloaders can be tailored to match the application's design language, providing a cohesive and branded user experience.

**Accessibility:**
1. An accessible preloader ensures that all users, including those using screen readers, are informed about loading processes, enhancing the inclusivity of the application.

**Feedback Loop:**
1. Provides immediate feedback to users about ongoing processes, such as form submissions or data fetching, making the application more interactive and responsive to user actions.

### Implementation Details (optional)

**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

### Screenshots

My Previous Works:-

https://github.com/harmeetsingh11/RefactorMate/assets/146121869/62a39800-604b-402b-82ba-adc07b6b1197

https://github.com/harmeetsingh11/RefactorMate/assets/146121869/d362b527-f359-48a9-8c2c-7e219bd8586a

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by harmeetsingh11** [comment]
@AsmitaMishra24 It's already implemented, therefore closing this issue.
