### ISSUE TITLE
[Feature]: Addition of a new page: ERROR 404

### ISSUE THREAD

**Issue by taneeshaa15** [harmeetsingh11/RefactorMate#83]
### Description

I will add a new error page so that the user can be directed to homepage when any certain page is removed or the user mistypes any url.

### Justification

This feature is necessary because:
1.) It will save time of users.
2.) Make this website user friendly.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by taneeshaa15** [comment]
@harmeetsingh11 Please assign me this issue under gssoc'24 .

**Comment by harmeetsingh11** [comment]
It is not needed, closing this issue.
