### ISSUE TITLE
[Feature]: Add a Contributors Page

### ISSUE THREAD

**Issue by Asymtode712** [harmeetsingh11/RefactorMate#88]
### Description

Currently our website don't a Contributors page and I would like to solve this problem by adding a separate Contributors page with total number of contributions done by each contributor

### Justification

A Contributors page is essential because it acknowledges and celebrates the efforts of those involved in a project, fostering a sense of community and motivation. It provides transparency and builds trust with users and stakeholders by clearly attributing contributions. Additionally, it facilitates networking among contributors and enhances their professional profiles by showcasing their involvement, ultimately encouraging further collaboration and development.

### Screenshots

![Screenshot_20240626-083514_Chrome](https://github.com/harmeetsingh11/RefactorMate/assets/115717746/87024227-a6c4-4838-a5b8-577117cf5fc0)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Asymtode712** [comment]
@harmeetsingh11 Please check this feature and please let me know if I can work on it

**Comment by harmeetsingh11** [comment]
@Asymtode712 which program you are a part of?

**Comment by Asymtode712** [comment]
@harmeetsingh11 GSSoC'24

**Comment by harmeetsingh11** [comment]
@Asymtode712 the issue has been assigned to you:)

**Comment by Asymtode712** [comment]
Hey @harmeetsingh11 , do you have a Linkedin handle??

**Comment by Asymtode712** [comment]
@harmeetsingh11 Does this look good to you??


https://github.com/user-attachments/assets/8b5599ef-47a7-4b97-8326-6ceb470d23c7

**Comment by harmeetsingh11** [comment]
@Asymtode712 yes, here's is my linkedin [profile](https://www.linkedin.com/in/harmeetsingh113) and all the social links are present in the `footer` section.
This looks awesome! Keep the great work. 👏💯

**Comment by harmeetsingh11** [comment]
@Asymtode712 please make sure, you have used Tailwindcss.

**Comment by Asymtode712** [comment]
Yes @harmeetsingh11 , I have used Tailwind CSS and i am going to create a PR soon

**Comment by Asymtode712** [comment]
Hey @harmeetsingh1 , Actually this was the problem why I wasn't able to find your linkedin handle😅:


https://github.com/user-attachments/assets/d70092e1-ef4a-48cc-ad7a-ca3d7d2e8abf

So currently I have discovered two issue:

- Minor fix: Change positioning of ScrolltoTop btn so that social links aren't overlapped
- The current contributors page lacks responsiveness for smaller screens...

Can I raise an issue for these??

**Comment by harmeetsingh11** [comment]
@Asymtode712 yes, sure you can raise the issue for that. Go for it.

In addition to above, can you resolve the error in PR #80 which occurs while running the backend, it may be related to the typescript configuration.
You can raise separate issue and PR for fixes, I will assign points for that don't worry.

**Comment by Asymtode712** [comment]
Sure @harmeetsingh11 , once I am done with my issue, I will check out for the problem in the referenced PR too.....
