### ISSUE TITLE
adding a contact us page  both functionality and ui

### ISSUE THREAD

**Issue by Isha1233** [harmeetsingh11/RefactorMate#94]
### Description

I will implement full frontend functionalities using react if and mail js .Make it easy for user to connect 

### Justification

help user to raise issue they facing while using website

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by Isha1233** [comment]
@harmeetsingh11 kindly assign this issue to me

**Comment by harmeetsingh11** [comment]
@Isha1233 it is not needed for this project as of now.
